import type { LucideIcon } from "lucide-react";
import {
  BatteryCharging,
  BriefcaseBusiness,
  ClipboardCheck,
  DraftingCompass,
  Factory,
  Gauge,
  Handshake,
  Headset,
  Layers3,
  Leaf,
  MapPinned,
  Network,
  Radio,
  Rocket,
  Route,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Sprout,
  Target,
  TrendingUp,
  Wrench,
} from "lucide-react";

export const iconMap = {
  radio: Radio,
  batteryCharging: BatteryCharging,
  sprout: Sprout,
  shield: Shield,
  clipboardCheck: ClipboardCheck,
  draftingCompass: DraftingCompass,
  rocket: Rocket,
  wrench: Wrench,
  gauge: Gauge,
  headset: Headset,
  briefcaseBusiness: BriefcaseBusiness,
  target: Target,
  shieldCheck: ShieldCheck,
  handshake: Handshake,
  trendingUp: TrendingUp,
  layers3: Layers3,
  slidersHorizontal: SlidersHorizontal,
  leaf: Leaf,
  route: Route,
  mapPinned: MapPinned,
  network: Network,
  factory: Factory,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;
